a=input("enter the sequence of first colors : ")
b=input("enter the sequence of second colors : ")
a=a.split(',')
b=b.split(',')
s1=set(a)
s2=set(b)
print(s1)
print(s2)
s3=s1.difference(s2)
print("the difference btw s1 and s2 :",s3)
